### ISSUE TITLE
unshortener should check if a given url redirects

### ISSUE THREAD

**Issue by AvianFlu** [Swizec/node-unshortener#3]
`unshortener` will try to expand any link regardless of whether or not there's actually a shortlink service involved - should a check be done at some point?

**Comment by Swizec** [comment]
It isn't likely that this could be checked any more efficiently than simply trying to expand the URL and seeing what happens. But I'll add some tests to make sure it's returning the proper URL even if you give it a long one.

**Comment by Swizec** [comment]
I implemented a simple heuristic so no attempt is made to unshorten URL's that are obviously not short.

**Comment by robbiet480** [comment]
Given a url such as http://rxt.gd/s (my personal link shortener) which points to http://t.co/Q84CbjdR (a link to http://www.youtube.com/watch?v=_7WIorjEKw8) it still won't get the actual link (the YouTube one). 

longurl.org provides a service which does successfully drill all the way down to the final URL. It should be easy to just keep drilling down the URL until you hit a 200 code since most URL shorteners use 301 redirects.
